Nacos:
  Addr: "115.190.57.118"
  Prot: 8848
  Namespace: ""
  DataId: "demo-config"
  Group: "DEFAULT_GROUP"

Mysql:
  Host: "115.190.57.118"
  Port: 3306
  User: "root"
  Password: "4ay1nkal3u8ed77y"
  Database: "zuoyeyue"

Redis:
  Host: "115.190.57.118"
  Port: 6379
  Password: "4ay1nkal3u8ed77y"
  Database: 0

RabbitMQ:
  Host: "115.190.57.118"
  Port: 5672
  User: "rabbitmq"
  Password: "rabbitmq"
  VHost: "yuhang"

AliPay:
  PrivateKey: "MIIEowIBAAKCAQEApyIS6kVIPWfzp4gbp6Mkl3CcgkOApl5/Fp00a0ZS06srrMuSiQKdIg3CqqrcSnrqpvKc8bE4k5NGQeIb0BlZfCd3jSLdYHf8QziOHdBMsOCi9iOYRtVeugJpAAgGDXbrxfrzIJtXVVlfOfdZMgURu1UPE1536IlZrYBHHdOVB/TZTlrbT8TiH3w/NCzBOxNBZQDrbXw9Ar9QAnrcCi2vLAYE6z80vKwmSx44+bbVBh2PcpUabkjB34GYqAZq2+4GwZuUHKd+xCvgfL3uYuFzLZs0JpOu17M8LyBrPAUxtGY5zhBKtTERfPxFvstxhXR5q/heycpUWzbmicagtFVg1wIDAQABAoIBABlf5PtIdYVNKQMAeSJkdIPBhyGH2hpoMmdeirzWunCEhmb/qUm/6ddnu2xp8HQmYUXjg8x2GZ7eN0Z9a7eWga2F2HLHHlEtJlGWXo1MOLiKAnPYR6BJeM5I22Qz06drrLQsO4lxzDqbDQgh85rShjSo31cTeqUFZWYgGav/mZrRY++LQmlxLGofFNHpMonG/j+2ZcZkctnX3MxEFI8wWI2hYlM2iwp1S3DoWKs55cirlAtH0ank6thbVvczqeD/p2uLC2AH59lAG3MC0TMCLfSJNZy+EiFCXBetE6QT18At0DDkEUTINyS/JXVKzNISgcsUErNB0akinVQTBagi6mECgYEA97TbG5E7MSLcrekag4iEnNB4fJm1bAAekXjhy3OEwpKwoiBFOo/6bAB0j+xt/bFUpdSg6C6gM0sxDxgJG0BmLVjERV9SY2EG72appV1Efl72gT7QdWbS4R3G4Atj+UIBZf3lfr71sj7ZGh9HvfQMyfDlS425jCN+ZWjMByTJk68CgYEArLqbVMxJoXcAb/mP/bYEUzVE1MuW04Yvkr55MQaBNLD0PFbDejnb0oXYFfJObIrvLaxDNdupdtMjofB0qgA+nWEpdhOlEx/W3PALoo/lExjdwtu60Hw8YMdS+YlAo7wXh26zTw2bV3/XRACov26jH4Gz/N4xsO8116mJm0fMx1kCgYAlA5huISCIMh5pulhk6URvrlMiw1Exxz7KHBcZcLSY4pSUVWAi5RrVgqfoTbsN2q68bO5yY2063PSCveO2d8QM6KPDff/wq7H+mgelly9B9uy82WcK9Ad07h8moW0Z9PwCgpMFgoFyViPY3G26+7nhfya0SIQ+ZZtgie1a7+tTLwKBgHVOwsGjgHotVNm3dwhK/sL4EYgnwIZlwpd5ztrx3PxJFYaJMncnJlji16+IAaUL8oZlULwaNAxkNvX7VXBDfELsQvlTPDAx1n30dSJxcZU3tRxqmISRa3wawwqAIatRyfULxLFyv0Z8p1kizXg9joGOWAvrZ3oP69RM6wzPhY75AoGBAIdHUTIWxI3NwFDUkb0AErexlOVGhIqK8MstYusOlvm+3sz8kJKgKXSUJ58gnX7tb1RxJAhzwpC0Op8gQeBFux6WwJOwHkOTyneswgmsDvGUja2AieqGTrC/Fvnszpbgs96y55D4p3MKnVIyTBFvQhzPNNR1UnLbr5sfk8FVkW+G"
  AppId: "9021000157678353"
  NotifyURL: "http://7a9785ac.r38.cpolar.top/notify/pay"
  ReturnURL: "http://7a9785ac.r38.cpolar.top/callback"
Consul:
  address: "115.190.57.118:8500"
  token: ""
  scheme: "http"
  service_name: "user-service"
  service_id: ""
  service_port: 8081
  service_addr: ""
  ttl: "5s"
  check_timeout: "3s"
  deregister_after: "30s"
  tags:
    - "grpc"
    - "v1.0"
  meta:
    protocol: "grpc"
    version: "1.0.0"

