// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: goods.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------goods--------------------------------
type Goods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        //id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     //名称
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` //价格
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`  //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

func (x *Goods) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Goods) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     //名称
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` //价格
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`  //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsReq) Reset() {
	*x = AddGoodsReq{}
	mi := &file_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsReq) ProtoMessage() {}

func (x *AddGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsReq.ProtoReflect.Descriptor instead.
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

func (x *AddGoodsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsResp) Reset() {
	*x = AddGoodsResp{}
	mi := &file_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsResp) ProtoMessage() {}

func (x *AddGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsResp.ProtoReflect.Descriptor instead.
func (*AddGoodsResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *AddGoodsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` //商品id
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                        //订单数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	mi := &file_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

func (x *OrderReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResp) Reset() {
	*x = OrderResp{}
	mi := &file_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResp) ProtoMessage() {}

func (x *OrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResp.ProtoReflect.Descriptor instead.
func (*OrderResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        //id
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` //价格
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsReq) Reset() {
	*x = UpdateGoodsReq{}
	mi := &file_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsReq) ProtoMessage() {}

func (x *UpdateGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsReq.ProtoReflect.Descriptor instead.
func (*UpdateGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsResp) Reset() {
	*x = UpdateGoodsResp{}
	mi := &file_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsResp) ProtoMessage() {}

func (x *UpdateGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsResp.ProtoReflect.Descriptor instead.
func (*UpdateGoodsResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGoodsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodsReq) Reset() {
	*x = DelGoodsReq{}
	mi := &file_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsReq) ProtoMessage() {}

func (x *DelGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsReq.ProtoReflect.Descriptor instead.
func (*DelGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{7}
}

func (x *DelGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodsResp) Reset() {
	*x = DelGoodsResp{}
	mi := &file_goods_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsResp) ProtoMessage() {}

func (x *DelGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsResp.ProtoReflect.Descriptor instead.
func (*DelGoodsResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{8}
}

func (x *DelGoodsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGoodsByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByIdReq) Reset() {
	*x = GetGoodsByIdReq{}
	mi := &file_goods_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdReq) ProtoMessage() {}

func (x *GetGoodsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdReq.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{9}
}

func (x *GetGoodsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGoodsByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         *Goods                 `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"` //goods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByIdResp) Reset() {
	*x = GetGoodsByIdResp{}
	mi := &file_goods_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdResp) ProtoMessage() {}

func (x *GetGoodsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdResp.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{10}
}

func (x *GetGoodsByIdResp) GetGoods() *Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type SearchGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` //page
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoodsReq) Reset() {
	*x = SearchGoodsReq{}
	mi := &file_goods_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsReq) ProtoMessage() {}

func (x *SearchGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsReq.ProtoReflect.Descriptor instead.
func (*SearchGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{11}
}

func (x *SearchGoodsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchGoodsReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         []*Goods               `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"` //goods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoodsResp) Reset() {
	*x = SearchGoodsResp{}
	mi := &file_goods_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsResp) ProtoMessage() {}

func (x *SearchGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsResp.ProtoReflect.Descriptor instead.
func (*SearchGoodsResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{12}
}

func (x *SearchGoodsResp) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type PayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	mi := &file_goods_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{13}
}

func (x *PayReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResp) Reset() {
	*x = PayResp{}
	mi := &file_goods_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResp) ProtoMessage() {}

func (x *PayResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResp.ProtoReflect.Descriptor instead.
func (*PayResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{14}
}

func (x *PayResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_goods_proto protoreflect.FileDescriptor

const file_goods_proto_rawDesc = "" +
	"\n" +
	"\vgoods.proto\x12\tecommerce\"W\n" +
	"\x05Goods\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\"M\n" +
	"\vAddGoodsReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\"(\n" +
	"\fAddGoodsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\bOrderReq\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"%\n" +
	"\tOrderResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x0eUpdateGoodsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"+\n" +
	"\x0fUpdateGoodsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1d\n" +
	"\vDelGoodsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"(\n" +
	"\fDelGoodsResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x0fGetGoodsByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10GetGoodsByIdResp\x12&\n" +
	"\x05goods\x18\x01 \x01(\v2\x10.ecommerce.GoodsR\x05goods\"8\n" +
	"\x0eSearchGoodsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"9\n" +
	"\x0fSearchGoodsResp\x12&\n" +
	"\x05goods\x18\x01 \x03(\v2\x10.ecommerce.GoodsR\x05goods\"\x18\n" +
	"\x06PayReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1b\n" +
	"\aPayResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xc9\x03\n" +
	"\x10EcommerceService\x12;\n" +
	"\bAddGoods\x12\x16.ecommerce.AddGoodsReq\x1a\x17.ecommerce.AddGoodsResp\x12D\n" +
	"\vUpdateGoods\x12\x19.ecommerce.UpdateGoodsReq\x1a\x1a.ecommerce.UpdateGoodsResp\x12;\n" +
	"\bDelGoods\x12\x16.ecommerce.DelGoodsReq\x1a\x17.ecommerce.DelGoodsResp\x12G\n" +
	"\fGetGoodsById\x12\x1a.ecommerce.GetGoodsByIdReq\x1a\x1b.ecommerce.GetGoodsByIdResp\x12D\n" +
	"\vSearchGoods\x12\x19.ecommerce.SearchGoodsReq\x1a\x1a.ecommerce.SearchGoodsResp\x125\n" +
	"\bAddOrder\x12\x13.ecommerce.OrderReq\x1a\x14.ecommerce.OrderResp\x12/\n" +
	"\x06AliPay\x12\x11.ecommerce.PayReq\x1a\x12.ecommerce.PayRespB\x04Z\x02./b\x06proto3"

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData []byte
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)))
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_goods_proto_goTypes = []any{
	(*Goods)(nil),            // 0: ecommerce.Goods
	(*AddGoodsReq)(nil),      // 1: ecommerce.AddGoodsReq
	(*AddGoodsResp)(nil),     // 2: ecommerce.AddGoodsResp
	(*OrderReq)(nil),         // 3: ecommerce.OrderReq
	(*OrderResp)(nil),        // 4: ecommerce.OrderResp
	(*UpdateGoodsReq)(nil),   // 5: ecommerce.UpdateGoodsReq
	(*UpdateGoodsResp)(nil),  // 6: ecommerce.UpdateGoodsResp
	(*DelGoodsReq)(nil),      // 7: ecommerce.DelGoodsReq
	(*DelGoodsResp)(nil),     // 8: ecommerce.DelGoodsResp
	(*GetGoodsByIdReq)(nil),  // 9: ecommerce.GetGoodsByIdReq
	(*GetGoodsByIdResp)(nil), // 10: ecommerce.GetGoodsByIdResp
	(*SearchGoodsReq)(nil),   // 11: ecommerce.SearchGoodsReq
	(*SearchGoodsResp)(nil),  // 12: ecommerce.SearchGoodsResp
	(*PayReq)(nil),           // 13: ecommerce.PayReq
	(*PayResp)(nil),          // 14: ecommerce.PayResp
}
var file_goods_proto_depIdxs = []int32{
	0,  // 0: ecommerce.GetGoodsByIdResp.goods:type_name -> ecommerce.Goods
	0,  // 1: ecommerce.SearchGoodsResp.goods:type_name -> ecommerce.Goods
	1,  // 2: ecommerce.EcommerceService.AddGoods:input_type -> ecommerce.AddGoodsReq
	5,  // 3: ecommerce.EcommerceService.UpdateGoods:input_type -> ecommerce.UpdateGoodsReq
	7,  // 4: ecommerce.EcommerceService.DelGoods:input_type -> ecommerce.DelGoodsReq
	9,  // 5: ecommerce.EcommerceService.GetGoodsById:input_type -> ecommerce.GetGoodsByIdReq
	11, // 6: ecommerce.EcommerceService.SearchGoods:input_type -> ecommerce.SearchGoodsReq
	3,  // 7: ecommerce.EcommerceService.AddOrder:input_type -> ecommerce.OrderReq
	13, // 8: ecommerce.EcommerceService.AliPay:input_type -> ecommerce.PayReq
	2,  // 9: ecommerce.EcommerceService.AddGoods:output_type -> ecommerce.AddGoodsResp
	6,  // 10: ecommerce.EcommerceService.UpdateGoods:output_type -> ecommerce.UpdateGoodsResp
	8,  // 11: ecommerce.EcommerceService.DelGoods:output_type -> ecommerce.DelGoodsResp
	10, // 12: ecommerce.EcommerceService.GetGoodsById:output_type -> ecommerce.GetGoodsByIdResp
	12, // 13: ecommerce.EcommerceService.SearchGoods:output_type -> ecommerce.SearchGoodsResp
	4,  // 14: ecommerce.EcommerceService.AddOrder:output_type -> ecommerce.OrderResp
	14, // 15: ecommerce.EcommerceService.AliPay:output_type -> ecommerce.PayResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
