// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: goods.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EcommerceService_AddGoods_FullMethodName     = "/ecommerce.EcommerceService/AddGoods"
	EcommerceService_UpdateGoods_FullMethodName  = "/ecommerce.EcommerceService/UpdateGoods"
	EcommerceService_DelGoods_FullMethodName     = "/ecommerce.EcommerceService/DelGoods"
	EcommerceService_GetGoodsById_FullMethodName = "/ecommerce.EcommerceService/GetGoodsById"
	EcommerceService_SearchGoods_FullMethodName  = "/ecommerce.EcommerceService/SearchGoods"
	EcommerceService_AddOrder_FullMethodName     = "/ecommerce.EcommerceService/AddOrder"
	EcommerceService_AliPay_FullMethodName       = "/ecommerce.EcommerceService/AliPay"
)

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	// -----------------------goods-----------------------
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
	UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error)
	DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error)
	GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error)
	SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error)
	AddOrder(ctx context.Context, in *OrderReq, opts ...grpc.CallOption) (*OrderResp, error)
	AliPay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsResp)
	err := c.cc.Invoke(ctx, EcommerceService_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoodsResp)
	err := c.cc.Invoke(ctx, EcommerceService_UpdateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelGoodsResp)
	err := c.cc.Invoke(ctx, EcommerceService_DelGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoodsByIdResp)
	err := c.cc.Invoke(ctx, EcommerceService_GetGoodsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGoodsResp)
	err := c.cc.Invoke(ctx, EcommerceService_SearchGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) AddOrder(ctx context.Context, in *OrderReq, opts ...grpc.CallOption) (*OrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResp)
	err := c.cc.Invoke(ctx, EcommerceService_AddOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) AliPay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayResp)
	err := c.cc.Invoke(ctx, EcommerceService_AliPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility.
type EcommerceServiceServer interface {
	// -----------------------goods-----------------------
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error)
	UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error)
	DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error)
	GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error)
	SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error)
	AddOrder(context.Context, *OrderReq) (*OrderResp, error)
	AliPay(context.Context, *PayReq) (*PayResp, error)
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEcommerceServiceServer struct{}

func (UnimplementedEcommerceServiceServer) AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedEcommerceServiceServer) UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGoods not implemented")
}
func (UnimplementedEcommerceServiceServer) DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelGoods not implemented")
}
func (UnimplementedEcommerceServiceServer) GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGoodsById not implemented")
}
func (UnimplementedEcommerceServiceServer) SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGoods not implemented")
}
func (UnimplementedEcommerceServiceServer) AddOrder(context.Context, *OrderReq) (*OrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedEcommerceServiceServer) AliPay(context.Context, *PayReq) (*PayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AliPay not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}
func (UnimplementedEcommerceServiceServer) testEmbeddedByValue()                          {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	// If the following call panics, it indicates UnimplementedEcommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_UpdateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).UpdateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_UpdateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).UpdateGoods(ctx, req.(*UpdateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_DelGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).DelGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_DelGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).DelGoods(ctx, req.(*DelGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_GetGoodsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).GetGoodsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_GetGoodsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).GetGoodsById(ctx, req.(*GetGoodsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SearchGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SearchGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SearchGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SearchGoods(ctx, req.(*SearchGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AddOrder(ctx, req.(*OrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_AliPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AliPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AliPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AliPay(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoods",
			Handler:    _EcommerceService_AddGoods_Handler,
		},
		{
			MethodName: "UpdateGoods",
			Handler:    _EcommerceService_UpdateGoods_Handler,
		},
		{
			MethodName: "DelGoods",
			Handler:    _EcommerceService_DelGoods_Handler,
		},
		{
			MethodName: "GetGoodsById",
			Handler:    _EcommerceService_GetGoodsById_Handler,
		},
		{
			MethodName: "SearchGoods",
			Handler:    _EcommerceService_SearchGoods_Handler,
		},
		{
			MethodName: "AddOrder",
			Handler:    _EcommerceService_AddOrder_Handler,
		},
		{
			MethodName: "AliPay",
			Handler:    _EcommerceService_AliPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
